# History of Neural Networks
* First Conceptualizes 1943
* First models were visualizations of perceptrions introduced in 1958 by Frank Rosenblatt
    * Belief that artificial neural networks (ANNs) would soon be able to translate languages on the fly.
* However, it lacked technology to actually get something to work. Period of time known as the "AI Winter"

**ImageNet 2012**  
Large-scale Visual Recognition Challenge. 
Reintroduced the idea of Neural Networks.

$$
y = w_0 + \sum{w_i x_i}
$$
Or
$$
y = \vec{w} * \vec{x}
$$ 

Multiple outputs of y:
$$
\bar{Y} = W \bar{X}
$$
Solving the weights:
$$
\bar{W} = \bar{Y}\bar{X}^{+}
$$

In [ ]:
import numpy as np
from sklearn.datasets import load_iris

#### Load Data
iris = load_iris()
X = iris.data
y = iris.target

#### Cross Validation (split data)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=20)

In [ ]:
#### Perceptron Model
from sklearn.linear_model import Perceptron

per_clf = Perceptron()
per_clf.fit(X_train, y_train)

#### Test the perceptron
y_pred = per_clf.predict(X_test)

#### Cross Validation (test data)
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.80      1.00      0.89         8
           1       0.82      0.82      0.82        11
           2       1.00      0.82      0.90        11

    accuracy                           0.87        30
   macro avg       0.87      0.88      0.87        30
weighted avg       0.88      0.87      0.87        30

[[8 0 0]
 [2 9 0]
 [0 2 9]]


Our test above wasn't very accurate. We could do better.

## Activation Functions
The __activation__ is the computed value of a neuron (or node)

For example,
$$
y_1 = w_0 \sum{w_{1i} x_i}
$$

An __activation function__ can adjust the value of the output neuron, depending on its value.  
$$
y_1 = \sigma \left( w_0 \sum{w_{1i} x_i} \right)
$$

Activation functions are generally non-linear.
Sometimes, the output of the activation function is a value within the range of that function n(linear activation function, or ReLu). These are great for regression networks.  

Let $z = w_0 + \sum{w_{1i} x_i}$

## Good for Linear Regressions 
#### 1. Linear Activation Function
Just a linear transformation of each y value. Takes the linear regression line and adjusts the slope.
$$y = \sigma(z) = \alpha z$$

#### 2. Rectified Linear Unit (ReLU)  
The max means that we keep our linear regression above zero, but after it is above zero, we follow the liner regression line.  
$$y = \sigma(z) = \max\{{0, z}\}$$


## Good for Classifications
Sometimes the output of the activation function is a value between 0 and 1. This essentially gives a probability, so it's good for classification models. 
#### 1. Step Function (aka Threshold Logic Unit (TLU))  
Gives a straight jump from 0 to 1.
$$ y = \sigma = \begin{cases}1  &\text{if }z \ge threshold \\ 0 & \text{if } z < threshold \end{cases} $$

#### 2. Sigmoid Function (aka Logical Function)  
Gives a gradual transition from 0 to 1.
$$
    y = \sigma(z) = \frac{1}{1 + e^{-z}}
$$

#### 3. Hyperbolic Tangent  
Acts like the sigmoid, but between -1 and 1 instead of 0 and 1.
$$
    y = \sigma(z) = \tanh{z} = \frac{e^{z} - e^{-z}}{e^z + e^{-z}}
$$
